### PR TITLE
Public key wif

### PR DESCRIPTION
**Pull request by kingsleyh**
This change provides a new wallet format:

```
{
  "public_key": "3187df5c25122c1130eec19fabc1725766b99ded9fa64659ed83d5c281c3fa3a25c1ca2c39ddda144351de2dda6c22be66194e1d1343d67578d3174a3927d24e",
  "wif": "VDBkYzY3MWJiY2JjZjdhYWRmY2M4OGRkMzJkZTk3MTdmM2NjZjk3M2I0MjBiN2QyZWFlMWYxZmY5NWQ5ZjNhYjhhMTRmN2M4",
  "address": "VDBkNTczOGQ1NmIzNmYwN2Y0Y2M1NzU0YWNiOTZkMGZkYWIwOWJiZjlhZjFiNjZk"
      }
```

private key and public key are standard ECDSA
wif and address are base64 encoded based on our own crypto

### CODE REVIEW

**Comment by tbrand** [comment]
Is `private key` still needed in the json? It seems be duplicated with wif. 🤔

**Comment by kingsleyh** [comment]
We could remove it if you want and just use wif

**Comment by tbrand** [comment]
Yeah, it's smart.

**Comment by kingsleyh** [comment]
ok - I will switch to using wif only and update here

**Comment by kingsleyh** [comment]
ok - refactored to remove private key from wallet and only use wif

**Pull request merged**
