### PR TITLE
Minimum number of connections

### PR DESCRIPTION
**Pull request by tbrand**
## Issues
- https://github.com/SushiCoinHQ/SushiCoin/issues/64

### CODE REVIEW

**Comment by tbrand** [comment]
@kingsleyh Please review and merge this PR if it's OK!

**Comment by kingsleyh** [comment]
When I start 3 nodes: 3000 (standalone), 3001, 3002, 3003 (all pointing at 3000) - when each node has a conn_min=20 

The first thing is - node 3003 on startup - says it connected to the 3000 ok, then it says the current connection 1 is less than 20 - so searches for nodes - and it finds 2 - 3002, 3003 which it says it's connecting to - however it only says successfully connected to 3002. Then it says current connection (2) is less than 20 - and it searches but again receives 3001 - which is says it's connecting to - but I never get a successful connection message

This seems like something is not working quite right.

screen shot 2018-02-14 at 05 59 18

3000 is 09f980072570e59fd94311f03c8e66d5
3001 is 411b6f2399bd6ace59a57f931bf7c7ef
3002 is 0600e7ee42edd756798c39cadf1437bd
3003 is 7ee2efec4adf4c27b685412784dea1c3

The second thing is that - even though 3001 wants a min of 20 - when it starts up there is only the primary on 3000 which it connected to. But when I add 3002, and 3003 - the node 3001 does not get updated about these - so it never adds them unless node 3001 is restarted. I think it would be nice if a new node would be able to be picked up by already running nodes somehow

The third thing is that - the primary node (3000) is never searching for connections - even though I specified min of 20 - maybe this is because it's the standalone one - not sure if that is right or not.

**Comment by kingsleyh** [comment]
Actually regarding the second issue - node 3002 did receive a new node notification when 3003 was added, however 3001 did not.

screen shot 2018-02-14 at 06 07 41

**Comment by tbrand** [comment]
> The first thing is - node 3003 on startup - says it connected to the 3000 ok, then it says the current connection 1 is less than 20 - so searches for nodes - and it finds 2 - 3002, 3003 which it says it's connecting to - however it only says successfully connected to 3002. Then it says current connection (2) is less than 20 - and it searches but again receives 3001 - which is says it's connecting to - but I never get a successful connection message

May be you did a typo at here

```
localhost
locahost
```

But it seems there is no error message. That's my bad. Will fix it.

> The second thing is that - even though 3001 wants a min of 20 - when it starts up there is only the primary on 3000 which it connected to. But when I add 3002, and 3003 - the node 3001 does not get updated about these - so it never adds them unless node 3001 is restarted.

That's a known thing for me since requesting new node list to others are triggered only when some node has been disconnected.
`--conn_min` only guarantees the number of **first** connections (and it's lazy), in this case, there are few nodes less than 20. So it give up to search them during the first phase.
If every node shares every node contexts and status, that's not p2p.
May be it is a not problem of the implementation but of the document. I will fix the docs.

> Actually regarding the second issue - node 3002 did receive a new node notification when 3003 was added, however 3001 did not.

Same as first one.

------

new tasks
- [ ] Fix `--conn_min` option's document

**Comment by tbrand** [comment]
I will work on detecting invalid public address at here. https://github.com/SushiCoinHQ/SushiCoin/issues/68
So let me fix it in the future.

**Comment by kingsleyh** [comment]
Ah yeah I totally did a typo!! Still not awake yet!!!

**Comment by kingsleyh** [comment]
Great work :)

**Pull request merged**
